# Generated by Django 4.2.6 on 2023-11-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_id", models.TextField(blank=True, null=True)),
                ("candidate_id", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
