# Generated by Django 4.2.6 on 2023-11-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_voted"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="email",
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
